name: Build Unreal Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    # runs-on: windows-latest
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cook, Stage & Package UE Project
        uses: ArmainAP/UE5-Build-Project@main
        with:
          RUNUAT_PATH: 'e:/Program Files/Epic Games/UE_5.5/Engine/Build/BatchFiles/RunUAT.bat'
          UPROJECT_PATH: '${{ github.workspace }}/ThirdPerson55.uproject'
          BUILD_CONFIG: Development
          PLATFORM: Win64
          CLEAN: true
          COOK: true
          STAGE: true
          PACKAGE: true
          PAK: true
          ARCHIVE: true
          ARCHIVE_PATH: 'e:/Temp/ThirdPerson55'
          NULLRHI: true
          EDITOR: true
